name: Documentation generation

on: [push, pull_request]

jobs:
  publish_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2'
          channel: 'stable'
      - run: flutter pub get
      - run: dart doc .
