name: flutter_iban_tools
description: "Flutter IBANTools is Flutter/Dart library for validation, creation and extraction of IBAN, BBAN and BIC/SWIFT numbers."
version: 0.1.0
homepage: https://github.com/Dennis-Mwea/flutter_iban_tools

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  dartdoc: ^8.0.7

flutter:
  uses-material-design: true
