import 'package:flutter_iban_tools/src/flutter_iban_tools.dart';
import 'package:flutter_iban_tools/src/models/country_spec.dart';

Map<String, CountrySpec> countrySpecs = <String, CountrySpec>{
  'AD': CountrySpec(
      chars: 24,
      sepa: true,
      ibanRegistry: true,
      bankIdentifier: '0-3',
      branchIdentifier: '4-7',
      accountIdentifier: '8-24',
      bbanRegexp: RegExp(r'^[0-9]{8}[A-Z0-9]{12}$')),
  'AE': CountrySpec(
      chars: 23,
      bbanRegexp: RegExp(r'^[0-9]{3}[0-9]{16}$'),
      ibanRegistry: true,
      bankIdentifier: '0-2',
      accountIdentifier: '7-23'),
  'AF': const CountrySpec(),
  'AG': const CountrySpec(),
  'AI': const CountrySpec(),
  'AL': CountrySpec(
      chars: 28,
      bbanRegexp: RegExp(r'^[0-9]{8}[A-Z0-9]{16}$'),
      ibanRegistry: true,
      branchIdentifier: '3-7',
      bankIdentifier: '0-2',
      accountIdentifier: '12-28'),
  'AM': const CountrySpec(),
  'AO': CountrySpec(chars: 25, bbanRegexp: RegExp(r'^[0-9]{21}$')),
  'AQ': const CountrySpec(),
  'AR': const CountrySpec(),
  'AS': const CountrySpec(),
  'AT': CountrySpec(
      chars: 20,
      bbanRegexp: RegExp(r'^[0-9]{16}$'),
      ibanRegistry: true,
      sepa: true,
      bankIdentifier: '0-4'),
  'AU': const CountrySpec(),
  'AW': const CountrySpec(),
  'AX': CountrySpec(
      chars: 18, bbanRegexp: RegExp(r'^[0-9]{14}$'), ibanRegistry: true),
  'AZ': CountrySpec(
      chars: 28,
      bbanRegexp: RegExp(r'^[A-Z]{4}[A-Z0-9]{20}$'),
      ibanRegistry: true,
      bankIdentifier: '0-3',
      accountIdentifier: '4-28'),
  'BA': CountrySpec(
      chars: 20,
      bbanRegexp: RegExp(r'^[0-9]{16}$'),
      bbanValidationFunc: checkMod9710BBAN,
      ibanRegistry: true,
      branchIdentifier: '3-5',
      bankIdentifier: '0-2'),
  'BB': const CountrySpec(),
  'BD': const CountrySpec(),
  'BE': CountrySpec(
      chars: 16,
      sepa: true,
      ibanRegistry: true,
      bankIdentifier: '0-2',
      accountIdentifier: '0-16',
      bbanRegexp: RegExp(r'^[0-9]{12}$'),
      bbanValidationFunc: checkBelgianBBAN),
  'BF': CountrySpec(chars: 28, bbanRegexp: RegExp(r'^[A-Z0-9]{2}[0-9]{22}$')),
  'BG': CountrySpec(
      chars: 22,
      bbanRegexp: RegExp(r'^[A-Z]{4}[0-9]{6}[A-Z0-9]{8}$'),
      ibanRegistry: true,
      sepa: true,
      branchIdentifier: '4-7',
      bankIdentifier: '0-3'),
  'BH': CountrySpec(
      chars: 22,
      bbanRegexp: RegExp(r'^[A-Z]{4}[A-Z0-9]{14}$'),
      ibanRegistry: true,
      bankIdentifier: '0-3',
      accountIdentifier: '8-22'),
  'BI': CountrySpec(
      chars: 27,
      bbanRegexp: RegExp(r'^[0-9]{23}$'),
      branchIdentifier: '5-9',
      bankIdentifier: '0-4',
      accountIdentifier: '14-27'),
  'BJ': CountrySpec(chars: 28, bbanRegexp: RegExp(r'^[A-Z0-9]{2}[0-9]{22}$')),
  'BL': CountrySpec(
      chars: 27, bbanRegexp: RegExp(r'^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$')),
  'BM': const CountrySpec(),
  'BN': const CountrySpec(),
  'BO': const CountrySpec(),
  'BQ': const CountrySpec(),
  'BR': CountrySpec(
      chars: 29,
      ibanRegistry: true,
      bankIdentifier: '0-7',
      branchIdentifier: '8-12',
      accountIdentifier: '17-29',
      bbanRegexp: RegExp(r'^[0-9]{23}[A-Z]{1}[A-Z0-9]{1}$')),
  'BS': const CountrySpec(),
  'BT': const CountrySpec(),
  'BV': const CountrySpec(),
  'BW': const CountrySpec(),
  'BY': CountrySpec(
      chars: 28,
      bbanRegexp: RegExp(r'^[A-Z]{4}[0-9]{4}[A-Z0-9]{16}$'),
      ibanRegistry: true,
      bankIdentifier: '0-3'),
  'BZ': const CountrySpec(),
  'CA': const CountrySpec(),
  'CC': const CountrySpec(),
  'CD': const CountrySpec(),
  'CF': CountrySpec(chars: 27, bbanRegexp: RegExp(r'^[0-9]{23}$')),
  'CG': CountrySpec(chars: 27, bbanRegexp: RegExp(r'^[0-9]{23}$')),
  'CH': CountrySpec(
      chars: 21,
      bbanRegexp: RegExp(r'^[0-9]{5}[A-Z0-9]{12}$'),
      ibanRegistry: true,
      sepa: true,
      bankIdentifier: '0-4'),
  'CI': CountrySpec(chars: 28, bbanRegexp: RegExp(r'^[A-Z]{1}[0-9]{23}$')),
  'CK': const CountrySpec(),
  'CL': const CountrySpec(),
  'CM': CountrySpec(chars: 27, bbanRegexp: RegExp(r'^[0-9]{23}$')),
  'CN': const CountrySpec(),
  'CO': const CountrySpec(),
  'CR': CountrySpec(
      chars: 22,
      bbanRegexp: RegExp(r'^[0-9]{18}$'),
      ibanRegistry: true,
      bankIdentifier: '0-3',
      accountIdentifier: '8-22'),
  'CU': const CountrySpec(),
  'CV': CountrySpec(chars: 25, bbanRegexp: RegExp(r'^[0-9]{21}$')),
  'CW': const CountrySpec(),
  'CX': const CountrySpec(),
  'CY': CountrySpec(
      chars: 28,
      sepa: true,
      ibanRegistry: true,
      bankIdentifier: '0-2',
      branchIdentifier: '3-7',
      accountIdentifier: '12-28',
      bbanRegexp: RegExp(r'^[0-9]{8}[A-Z0-9]{16}$')),
  'CZ': CountrySpec(
      chars: 24,
      bbanRegexp: RegExp(r'^[0-9]{20}$'),
      bbanValidationFunc: checkCzechAndSlovakBBAN,
      ibanRegistry: true,
      sepa: true,
      bankIdentifier: '0-3'),
  'DE': CountrySpec(
      chars: 22,
      bbanRegexp: RegExp(r'^[0-9]{18}$'),
      ibanRegistry: true,
      sepa: true,
      bankIdentifier: '0-7',
      accountIdentifier: '13-22'),
  'DJ': CountrySpec(
      chars: 27,
      bbanRegexp: RegExp(r'^[0-9]{23}$'),
      branchIdentifier: '5-9',
      bankIdentifier: '0-4',
      accountIdentifier: '14-27'),
  'DK': CountrySpec(
      chars: 18,
      bbanRegexp: RegExp(r'^[0-9]{14}$'),
      ibanRegistry: true,
      sepa: true,
      bankIdentifier: '0-3',
      accountIdentifier: '4-18'),
  'DM': const CountrySpec(),
  'DO': CountrySpec(
      chars: 28,
      bbanRegexp: RegExp(r'^[A-Z]{4}[0-9]{20}$'),
      ibanRegistry: true,
      bankIdentifier: '0-3',
      accountIdentifier: '8-28'),
  'DZ': CountrySpec(chars: 26, bbanRegexp: RegExp(r'^[0-9]{22}$')),
  'EC': const CountrySpec(),
  'EE': CountrySpec(
      chars: 20,
      sepa: true,
      ibanRegistry: true,
      bankIdentifier: '0-1',
      accountIdentifier: '8-20',
      bbanRegexp: RegExp(r'^[0-9]{16}$'),
      bbanValidationFunc: checkEstonianBBAN),
  'EG': CountrySpec(
      chars: 29,
      bbanRegexp: RegExp(r'^[0-9]{25}'),
      ibanRegistry: true,
      branchIdentifier: '4-7',
      bankIdentifier: '0-3',
      accountIdentifier: '17-29'),
  'EH': const CountrySpec(),
  'ER': const CountrySpec(),
  'ES': CountrySpec(
      chars: 24,
      sepa: true,
      ibanRegistry: true,
      bankIdentifier: '0-3',
      branchIdentifier: '4-7',
      accountIdentifier: '14-24',
      bbanValidationFunc: checkSpainBBAN,
      bbanRegexp: RegExp(r'^[0-9]{20}$')),
  'ET': const CountrySpec(),
  'FI': CountrySpec(
      chars: 18,
      bbanRegexp: RegExp(r'^[0-9]{14}$'),
      ibanRegistry: true,
      sepa: true,
      bankIdentifier: '0-2',
      accountIdentifier: '0-0'),
  'FJ': const CountrySpec(),
  'FK': CountrySpec(
      chars: 18,
      bbanRegexp: RegExp(r'^[A-Z]{2}[0-9]{12}$'),
      bankIdentifier: '0-1',
      accountIdentifier: '6-18'),
  'FM': const CountrySpec(),
  'FO': CountrySpec(
      chars: 18,
      bbanRegexp: RegExp(r'^[0-9]{14}$'),
      ibanRegistry: true,
      bankIdentifier: '0-3',
      accountIdentifier: '4-18'),
  'FR': CountrySpec(
      chars: 27,
      sepa: true,
      ibanRegistry: true,
      bankIdentifier: '0-4',
      branchIdentifier: '5-9',
      accountIdentifier: '14-24',
      bbanValidationFunc: checkFrenchBBAN,
      bbanRegexp: RegExp(r'^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$')),
  'GA': CountrySpec(chars: 27, bbanRegexp: RegExp(r'^[0-9]{23}$')),
  'GB': CountrySpec(
      chars: 22,
      bbanRegexp: RegExp(r'^[A-Z]{4}[0-9]{14}$'),
      ibanRegistry: true,
      sepa: true,
      branchIdentifier: '4-9',
      bankIdentifier: '0-3'),
  'GD': const CountrySpec(),
  'GE': CountrySpec(
      chars: 22,
      bbanRegexp: RegExp(r'^[A-Z0-9]{2}[0-9]{16}$'),
      ibanRegistry: true,
      bankIdentifier: '0-1',
      accountIdentifier: '6-22'),
  'GF': CountrySpec(
      chars: 27,
      bbanRegexp: RegExp(r'^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$'),
      ibanRegistry: true),
  'GG': const CountrySpec(),
  'GH': const CountrySpec(),
  'GI': CountrySpec(
      chars: 23,
      bbanRegexp: RegExp(r'^[A-Z]{4}[A-Z0-9]{15}$'),
      ibanRegistry: true,
      sepa: true,
      bankIdentifier: '0-3',
      accountIdentifier: '8-23'),
  'GL': CountrySpec(
      chars: 18,
      bbanRegexp: RegExp(r'^[0-9]{14}$'),
      ibanRegistry: true,
      bankIdentifier: '0-3',
      accountIdentifier: '4-18'),
  'GM': const CountrySpec(),
  'GN': const CountrySpec(),
  'GP': CountrySpec(
      chars: 27,
      bbanRegexp: RegExp(r'^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$'),
      ibanRegistry: true),
  'GQ': CountrySpec(chars: 27, bbanRegexp: RegExp(r'^[0-9]{23}$')),
  'GR': CountrySpec(
      chars: 27,
      sepa: true,
      ibanRegistry: true,
      bankIdentifier: '0-2',
      branchIdentifier: '3-6',
      accountIdentifier: '7-27',
      bbanRegexp: RegExp(r'^[0-9]{7}[A-Z0-9]{16}$')),
  'GS': const CountrySpec(),
  'GT': CountrySpec(
      chars: 28,
      bbanRegexp: RegExp(r'^[A-Z0-9]{24}$'),
      ibanRegistry: true,
      bankIdentifier: '0-3',
      accountIdentifier: '8-28'),
  'GU': const CountrySpec(),
  'GW': CountrySpec(chars: 25, bbanRegexp: RegExp(r'^[A-Z]{2}[0-9]{19}$')),
  'GY': const CountrySpec(),
  'HK': const CountrySpec(),
  'HM': const CountrySpec(),
  'HN': CountrySpec(chars: 28, bbanRegexp: RegExp(r'^[A-Z]{4}[0-9]{20}$')),
  'HR': CountrySpec(
      chars: 21,
      bbanRegexp: RegExp(r'^[0-9]{17}$'),
      bbanValidationFunc: checkCroatianBBAN,
      ibanRegistry: true,
      sepa: true,
      bankIdentifier: '0-6'),
  'HT': const CountrySpec(),
  'HU': CountrySpec(
      chars: 28,
      sepa: true,
      ibanRegistry: true,
      bankIdentifier: '0-2',
      branchIdentifier: '3-6',
      bbanRegexp: RegExp(r'^[0-9]{24}$'),
      bbanValidationFunc: checkHungarianBBAN),
  'ID': const CountrySpec(),
  'IE': CountrySpec(
      chars: 22,
      bbanRegexp: RegExp(r'^[A-Z0-9]{4}[0-9]{14}$'),
      ibanRegistry: true,
      sepa: true,
      branchIdentifier: '4-9',
      bankIdentifier: '0-3'),
  'IL': CountrySpec(
      chars: 23,
      bbanRegexp: RegExp(r'^[0-9]{19}$'),
      ibanRegistry: true,
      branchIdentifier: '3-5',
      bankIdentifier: '0-2'),
  'IM': const CountrySpec(),
  'IN': const CountrySpec(),
  'IO': const CountrySpec(),
  'IQ': CountrySpec(
      chars: 23,
      ibanRegistry: true,
      branchIdentifier: '4-6',
      bankIdentifier: '0-3',
      accountIdentifier: '11-23',
      bbanRegexp: RegExp(r'^[A-Z]{4}[0-9]{15}$')),
  'IR': CountrySpec(chars: 26, bbanRegexp: RegExp(r'^[0-9]{22}$')),
  'IS': CountrySpec(
      chars: 26,
      ibanRegistry: true,
      sepa: true,
      branchIdentifier: '2-3',
      bankIdentifier: '0-1',
      bbanRegexp: RegExp(r'^[0-9]{22}$')),
  'IT': CountrySpec(
      chars: 27,
      sepa: true,
      ibanRegistry: true,
      bankIdentifier: '1-5',
      branchIdentifier: '6-10',
      accountIdentifier: '4-27',
      bbanRegexp: RegExp(r'^[A-Z]{1}[0-9]{10}[A-Z0-9]{12}$')),
  'JE': const CountrySpec(),
  'JM': const CountrySpec(),
  'JO': CountrySpec(
      chars: 30,
      ibanRegistry: true,
      branchIdentifier: '4-7',
      bankIdentifier: '4-7',
      bbanRegexp: RegExp(r'^[A-Z]{4}[0-9]{4}[A-Z0-9]{18}$')),
  'JP': const CountrySpec(),
  'KE': const CountrySpec(),
  'KG': const CountrySpec(),
  'KH': const CountrySpec(),
  'KI': const CountrySpec(),
  'KM': CountrySpec(chars: 27, bbanRegexp: RegExp(r'^[0-9]{23}$')),
  'KN': const CountrySpec(),
  'KP': const CountrySpec(),
  'KR': const CountrySpec(),
  'KW': CountrySpec(
      chars: 30,
      bbanRegexp: RegExp(r'^[A-Z]{4}[A-Z0-9]{22}$'),
      ibanRegistry: true,
      bankIdentifier: '0-3',
      accountIdentifier: '20-30'),
  'KY': const CountrySpec(),
  'KZ': CountrySpec(
      chars: 20,
      bbanRegexp: RegExp(r'^[0-9]{3}[A-Z0-9]{13}$'),
      ibanRegistry: true,
      bankIdentifier: '0-2',
      accountIdentifier: '0-20'),
  'LA': const CountrySpec(),
  'LB': CountrySpec(
      chars: 28,
      bbanRegexp: RegExp(r'^[0-9]{4}[A-Z0-9]{20}$'),
      ibanRegistry: true,
      bankIdentifier: '0-3',
      accountIdentifier: '14-28'),
  'LC': CountrySpec(
      chars: 32,
      ibanRegistry: true,
      bankIdentifier: '0-3',
      accountIdentifier: '8-32',
      bbanRegexp: RegExp(r'^[A-Z]{4}[A-Z0-9]{24}$')),
  'LI': CountrySpec(
      chars: 21,
      bbanRegexp: RegExp(r'^[0-9]{5}[A-Z0-9]{12}$'),
      ibanRegistry: true,
      sepa: true,
      bankIdentifier: '0-4'),
  'LK': const CountrySpec(),
  'LR': const CountrySpec(),
  'LS': const CountrySpec(),
  'LT': CountrySpec(
      chars: 20,
      bbanRegexp: RegExp(r'^[0-9]{16}$'),
      ibanRegistry: true,
      sepa: true,
      bankIdentifier: '0-4'),
  'LU': CountrySpec(
      chars: 20,
      bbanRegexp: RegExp(r'^[0-9]{3}[A-Z0-9]{13}$'),
      ibanRegistry: true,
      sepa: true,
      bankIdentifier: '0-2'),
  'LV': CountrySpec(
      chars: 21,
      ibanRegistry: true,
      sepa: true,
      bankIdentifier: '0-3',
      accountIdentifier: '0-21',
      bbanRegexp: RegExp(r'^[A-Z]{4}[A-Z0-9]{13}$')),
  'LY': CountrySpec(
      chars: 25,
      bbanRegexp: RegExp(r'^[0-9]{21}$'),
      ibanRegistry: true,
      branchIdentifier: '3-5',
      bankIdentifier: '0-2',
      accountIdentifier: '10-25'),
  'MA': CountrySpec(chars: 28, bbanRegexp: RegExp(r'^[0-9]{24}$')),
  'MC': CountrySpec(
      chars: 27,
      sepa: true,
      ibanRegistry: true,
      bankIdentifier: '0-4',
      branchIdentifier: '5-9',
      bbanValidationFunc: checkFrenchBBAN,
      bbanRegexp: RegExp(r'^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$')),
  'MD': CountrySpec(
      chars: 24,
      bbanRegexp: RegExp(r'^[A-Z0-9]{2}[A-Z0-9]{18}$'),
      ibanRegistry: true,
      bankIdentifier: '0-1',
      accountIdentifier: '6-24'),
  'ME': CountrySpec(
      chars: 22,
      ibanRegistry: true,
      bankIdentifier: '0-2',
      accountIdentifier: '4-22',
      bbanRegexp: RegExp(r'^[0-9]{18}$'),
      bbanValidationFunc: checkMod9710BBAN),
  'MF': CountrySpec(
      chars: 27,
      bbanRegexp: RegExp(r'^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$'),
      ibanRegistry: true),
  'MG': CountrySpec(chars: 27, bbanRegexp: RegExp(r'^[0-9]{23}$')),
  'MH': const CountrySpec(),
  'MK': CountrySpec(
      chars: 19,
      bbanRegexp: RegExp(r'^[0-9]{3}[A-Z0-9]{10}[0-9]{2}$'),
      bbanValidationFunc: checkMod9710BBAN,
      ibanRegistry: true,
      bankIdentifier: '0-2'),
  'ML': CountrySpec(chars: 28, bbanRegexp: RegExp(r'^[A-Z0-9]{2}[0-9]{22}$')),
  'MM': const CountrySpec(),
  'MN': CountrySpec(
      chars: 20,
      bbanRegexp: RegExp(r'^[0-9]{16}$'),
      ibanRegistry: true,
      bankIdentifier: '0-3',
      accountIdentifier: '8-20'),
  'MO': const CountrySpec(),
  'MP': const CountrySpec(),
  'MQ': CountrySpec(
      chars: 27,
      bbanRegexp: RegExp(r'^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$'),
      ibanRegistry: true),
  'MR': CountrySpec(
      chars: 27,
      bbanRegexp: RegExp(r'^[0-9]{23}$'),
      ibanRegistry: true,
      branchIdentifier: '5-9',
      bankIdentifier: '0-4',
      accountIdentifier: '4-27'),
  'MS': const CountrySpec(),
  'MT': CountrySpec(
      chars: 31,
      sepa: true,
      ibanRegistry: true,
      bankIdentifier: '0-3',
      branchIdentifier: '4-8',
      accountIdentifier: '15-31',
      bbanRegexp: RegExp(r'^[A-Z]{4}[0-9]{5}[A-Z0-9]{18}$')),
  'MU': CountrySpec(
      chars: 30,
      ibanRegistry: true,
      bankIdentifier: '0-5',
      branchIdentifier: '6-7',
      accountIdentifier: '0-30',
      bbanRegexp: RegExp(r'^[A-Z]{4}[0-9]{19}[A-Z]{3}$')),
  'MV': const CountrySpec(),
  'MW': const CountrySpec(),
  'MX': const CountrySpec(),
  'MY': const CountrySpec(),
  'MZ': CountrySpec(chars: 25, bbanRegexp: RegExp(r'^[0-9]{21}$')),
  'NA': const CountrySpec(),
  'NC': CountrySpec(
      chars: 27,
      bbanRegexp: RegExp(r'^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$'),
      ibanRegistry: true),
  'NE': CountrySpec(chars: 28, bbanRegexp: RegExp(r'^[A-Z]{2}[0-9]{22}$')),
  'NF': const CountrySpec(),
  'NG': const CountrySpec(),
  'NI': CountrySpec(
      chars: 28,
      bbanRegexp: RegExp(r'^[A-Z]{4}[0-9]{20}$'),
      bankIdentifier: '0-3',
      ibanRegistry: true,
      accountIdentifier: '8-28'),
  'NL': CountrySpec(
      chars: 18,
      bbanRegexp: RegExp(r'^[A-Z]{4}[0-9]{10}$'),
      ibanRegistry: true,
      sepa: true,
      bankIdentifier: '0-3',
      accountIdentifier: '8-18'),
  'NO': CountrySpec(
      chars: 15,
      sepa: true,
      ibanRegistry: true,
      bankIdentifier: '0-3',
      accountIdentifier: '4-15',
      bbanRegexp: RegExp(r'^[0-9]{11}$'),
      bbanValidationFunc: checkNorwayBBAN),
  'NP': const CountrySpec(),
  'NR': const CountrySpec(),
  'NU': const CountrySpec(),
  'NZ': const CountrySpec(),
  'OM': CountrySpec(
      chars: 23,
      bbanRegexp: RegExp(r'^[0-9]{3}[A-Z0-9]{16}$'),
      ibanRegistry: true,
      sepa: false,
      bankIdentifier: '0-2'),
  'PA': const CountrySpec(),
  'PE': const CountrySpec(),
  'PF': CountrySpec(
      chars: 27,
      bbanRegexp: RegExp(r'^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$'),
      ibanRegistry: true),
  'PG': const CountrySpec(),
  'PH': const CountrySpec(),
  'PK': CountrySpec(
      chars: 24,
      bbanRegexp: RegExp(r'^[A-Z0-9]{4}[0-9]{16}$'),
      ibanRegistry: true,
      bankIdentifier: '0-3'),
  'PL': CountrySpec(
      chars: 28,
      sepa: true,
      ibanRegistry: true,
      branchIdentifier: '0-7',
      accountIdentifier: '2-28',
      bbanRegexp: RegExp(r'^[0-9]{24}$'),
      bbanValidationFunc: checkPolandBBAN),
  'PM': CountrySpec(
      chars: 27,
      bbanRegexp: RegExp(r'^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$'),
      ibanRegistry: true),
  'PN': const CountrySpec(),
  'PR': const CountrySpec(),
  'PS': CountrySpec(
      chars: 29,
      bbanRegexp: RegExp(r'^[A-Z0-9]{4}[0-9]{21}$'),
      ibanRegistry: true,
      bankIdentifier: '0-3',
      accountIdentifier: '17-29'),
  'PT': CountrySpec(
      chars: 25,
      bbanRegexp: RegExp(r'^[0-9]{21}$'),
      bbanValidationFunc: checkMod9710BBAN,
      ibanRegistry: true,
      sepa: true,
      bankIdentifier: '0-3'),
  'PW': const CountrySpec(),
  'PY': const CountrySpec(),
  'QA': CountrySpec(
      chars: 29,
      bbanRegexp: RegExp(r'^[A-Z]{4}[A-Z0-9]{21}$'),
      ibanRegistry: true,
      bankIdentifier: '0-3',
      accountIdentifier: '8-29'),
  'RE': CountrySpec(
      chars: 27,
      bbanRegexp: RegExp(r'^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$'),
      ibanRegistry: true),
  'RO': CountrySpec(
      chars: 24,
      bbanRegexp: RegExp(r'^[A-Z]{4}[A-Z0-9]{16}$'),
      ibanRegistry: true,
      sepa: true,
      bankIdentifier: '0-3',
      accountIdentifier: '0-24'),
  'RS': CountrySpec(
      chars: 22,
      bbanRegexp: RegExp(r'^[0-9]{18}$'),
      bbanValidationFunc: checkMod9710BBAN,
      ibanRegistry: true,
      bankIdentifier: '0-2'),
  'RU': CountrySpec(
      chars: 33,
      ibanRegistry: true,
      bankIdentifier: '0-8',
      branchIdentifier: '9-13',
      accountIdentifier: '13-33',
      bbanRegexp: RegExp(r'^[0-9]{14}[A-Z0-9]{15}$')),
  'RW': const CountrySpec(),
  'SA': CountrySpec(
      chars: 24,
      bbanRegexp: RegExp(r'^[0-9]{2}[A-Z0-9]{18}$'),
      ibanRegistry: true,
      bankIdentifier: '0-1',
      accountIdentifier: '12-24'),
  'SB': const CountrySpec(),
  'SC': CountrySpec(
      chars: 31,
      ibanRegistry: true,
      bankIdentifier: '0-5',
      branchIdentifier: '6-7',
      accountIdentifier: '12-28',
      bbanRegexp: RegExp(r'^[A-Z]{4}[0-9]{20}[A-Z]{3}$')),
  'SD': CountrySpec(
      chars: 18,
      bbanRegexp: RegExp(r'^[0-9]{14}$'),
      ibanRegistry: true,
      bankIdentifier: '0-1',
      accountIdentifier: '6-18'),
  'SE': CountrySpec(
      chars: 24,
      bbanRegexp: RegExp(r'^[0-9]{20}$'),
      ibanRegistry: true,
      sepa: true,
      bankIdentifier: '0-2'),
  'SG': const CountrySpec(),
  'SH': const CountrySpec(),
  'SI': CountrySpec(
      chars: 19,
      sepa: true,
      ibanRegistry: true,
      bankIdentifier: '0-1',
      branchIdentifier: '2-4',
      accountIdentifier: '9-16',
      bbanRegexp: RegExp(r'^[0-9]{15}$'),
      bbanValidationFunc: checkMod9710BBAN),
  'SJ': const CountrySpec(),
  'SK': CountrySpec(
      chars: 24,
      bbanRegexp: RegExp(r'^[0-9]{20}$'),
      bbanValidationFunc: checkCzechAndSlovakBBAN,
      ibanRegistry: true,
      sepa: true),
  'SL': const CountrySpec(),
  'SM': CountrySpec(
      chars: 27,
      bbanRegexp: RegExp(r'^[A-Z]{1}[0-9]{10}[A-Z0-9]{12}$'),
      ibanRegistry: true,
      sepa: true,
      branchIdentifier: '6-10'),
  'SN': CountrySpec(chars: 28, bbanRegexp: RegExp(r'^[A-Z]{2}[0-9]{22}$')),
  'SO': CountrySpec(
      chars: 23,
      bbanRegexp: RegExp(r'^[0-9]{19}$'),
      ibanRegistry: true,
      branchIdentifier: '4-6',
      accountIdentifier: '11-23'),
  'SR': const CountrySpec(),
  'SS': const CountrySpec(),
  'ST': CountrySpec(
      chars: 25,
      bbanRegexp: RegExp(r'^[0-9]{21}$'),
      ibanRegistry: true,
      branchIdentifier: '4-7'),
  'SV': CountrySpec(
      chars: 28,
      bbanRegexp: RegExp(r'^[A-Z]{4}[0-9]{20}$'),
      ibanRegistry: true,
      accountIdentifier: '8-28'),
  'SX': const CountrySpec(),
  'SY': const CountrySpec(),
  'SZ': const CountrySpec(),
  'TC': const CountrySpec(),
  'TD': CountrySpec(chars: 27, bbanRegexp: RegExp(r'^[0-9]{23}$')),
  'TF': CountrySpec(
      chars: 27,
      bbanRegexp: RegExp(r'^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$'),
      ibanRegistry: true),
  'TG': CountrySpec(chars: 28, bbanRegexp: RegExp(r'^[A-Z]{2}[0-9]{22}$')),
  'TH': const CountrySpec(),
  'TJ': const CountrySpec(),
  'TK': const CountrySpec(),
  'TL': CountrySpec(
      chars: 23,
      bbanRegexp: RegExp(r'^[0-9]{19}$'),
      ibanRegistry: true,
      accountIdentifier: '4-23'),
  'TM': const CountrySpec(),
  'TN': CountrySpec(
      chars: 24,
      bbanRegexp: RegExp(r'^[0-9]{20}$'),
      ibanRegistry: true,
      branchIdentifier: '2-4',
      accountIdentifier: '4-24'),
  'TO': const CountrySpec(),
  'TR': CountrySpec(
      chars: 26,
      bbanRegexp: RegExp(r'^[0-9]{5}[A-Z0-9]{17}$'),
      ibanRegistry: true),
  'TT': const CountrySpec(),
  'TV': const CountrySpec(),
  'TW': const CountrySpec(),
  'TZ': const CountrySpec(),
  'UA': CountrySpec(
      chars: 29,
      bbanRegexp: RegExp(r'^[0-9]{6}[A-Z0-9]{19}$'),
      ibanRegistry: true,
      accountIdentifier: '15-29'),
  'UG': const CountrySpec(),
  'UM': const CountrySpec(),
  'US': const CountrySpec(),
  'UY': const CountrySpec(),
  'UZ': const CountrySpec(),
  'VA': CountrySpec(
      chars: 22,
      bbanRegexp: RegExp(r'^[0-9]{18}'),
      ibanRegistry: true,
      sepa: true,
      accountIdentifier: '7-22'),
  'VC': const CountrySpec(),
  'VE': const CountrySpec(),
  'VG': CountrySpec(
      chars: 24,
      bbanRegexp: RegExp(r'^[A-Z0-9]{4}[0-9]{16}$'),
      ibanRegistry: true,
      accountIdentifier: '8-24'),
  'VI': const CountrySpec(),
  'VN': const CountrySpec(),
  'VU': const CountrySpec(),
  'WF': CountrySpec(
      chars: 27,
      bbanRegexp: RegExp(r'^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$'),
      ibanRegistry: true),
  'WS': const CountrySpec(),
  'XK': CountrySpec(
      chars: 20,
      bbanRegexp: RegExp(r'^[0-9]{16}$'),
      ibanRegistry: true,
      branchIdentifier: '2-3',
      accountIdentifier: '4-20'),
  'YE': const CountrySpec(),
  'YT': CountrySpec(
      chars: 27,
      bbanRegexp: RegExp(r'^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$'),
      ibanRegistry: true),
  'ZA': const CountrySpec(),
  'ZM': const CountrySpec(),
  'ZW': const CountrySpec(),
};
